package frc.robot;

import static edu.wpi.first.units.Units.*;

import java.io.IOException;
import java.nio.file.Path;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.hardware.*;
import com.ctre.phoenix6.signals.*;
import com.ctre.phoenix6.swerve.*;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.*;
import com.fasterxml.jackson.databind.ObjectMapper;

import edu.wpi.first.apriltag.AprilTagFieldLayout;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation3d;
import edu.wpi.first.math.geometry.Transform3d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.trajectory.TrapezoidProfile;
import edu.wpi.first.units.measure.*;
import frc.robot.subsystems.drive.Drivetrain;
import frc.util.COTSFalconSwerveConstants;

// TODO: Remove duplicates
import static edu.wpi.first.units.Units.*;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;

import javax.xml.transform.TransformerFactory;

import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.apriltag.AprilTagFieldLayout;
import edu.wpi.first.apriltag.AprilTag;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Rotation3d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.geometry.Transform3d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.trajectory.TrapezoidProfile;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.wpilibj.Filesystem;
import frc.util.COTSFalconSwerveConstants;
import static edu.wpi.first.units.Units.*;
// import static frc.robot.Constants.Swerve.angleGearRatio;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.hardware.*;
import com.ctre.phoenix6.signals.*;
import com.ctre.phoenix6.swerve.*;
import com.fasterxml.jackson.databind.ObjectMapper;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.*;

// Generated by the 2026 Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class Constants {
        public static final String kRobotIdFile = "/home/lvuser/id.txt";
        public static final String kCurrentLogFolder = "/home/lvuser/currentLogs";
        public static final double kNominalVoltage = 12.0;
        public static final int kCANTimeoutMs = 250;
        public static final double kTimestepSeconds = 0.02;
        public static final double kInchesToMeters = 0.0254;
        public static final double kRIOLoopTime = 0.02;
        // Both sets of gains need to be tuned to your individual robot.

        // Motor constants
        // TODO: Set these to the right values
        public static final double kFalconSensorUnitsPerRotation = 2048; // pulses per rotation
        public static final double kFalconWindingsResistanceOhms = 12.0 / 257;
        public static final double kFalconTorquePerAmp = 4.69 / 257;
        public static final double kFalconOutputUnitsFull = 1023;
        public static final double kFalconOutputUnitsPerVolt = kFalconOutputUnitsFull / kNominalVoltage;
        public static final double kFalconFreeSpeedRotationsPerSecond = 6380.0 / 60.0;
        public static final double kSecondsPer100Ms = 0.1;

        public static final double k775FreeSpeedRotationsPerSecond = 18730.0 / 60.0;

        public static final COTSFalconSwerveConstants chosenModule = COTSFalconSwerveConstants
                        .SDSMK5n(COTSFalconSwerveConstants.driveGearRatios.SDSMK5n_L2);

        // The steer motor uses any SwerveModule.SteerRequestType control request with
        // the
        // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
        private static final Slot0Configs steerGains = new Slot0Configs()
                        .withKP(20).withKI(0.1).withKD(0.5)
                        .withKS(0.1).withKV(2.49).withKA(0)
                        .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
        // When using closed-loop control, the drive motor uses the control
        // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
        private static final Slot0Configs driveGains = new Slot0Configs()
                        .withKP(0.1).withKI(0).withKD(0)
                        .withKS(0).withKV(0.124);

        // The closed-loop output type to use for the steer motors;
        // This affects the PID/FF gains for the steer motors
        private static final ClosedLoopOutputType kSteerClosedLoopOutput = ClosedLoopOutputType.Voltage;
        // The closed-loop output type to use for the drive motors;
        // This affects the PID/FF gains for the drive motors
        private static final ClosedLoopOutputType kDriveClosedLoopOutput = ClosedLoopOutputType.Voltage;

        // The type of motor used for the drive motor
        private static final DriveMotorArrangement kDriveMotorType = DriveMotorArrangement.TalonFX_Integrated;
        // The type of motor used for the drive motor
        private static final SteerMotorArrangement kSteerMotorType = SteerMotorArrangement.TalonFX_Integrated;

        // The remote sensor feedback type to use for the steer motors;
        // When not Pro-licensed, Fused*/Sync* automatically fall back to Remote*
        private static final SteerFeedbackType kSteerFeedbackType = SteerFeedbackType.FusedCANcoder;

        // The stator current at which the wheels start to slip;
        // This needs to be tuned to your individual robot
        private static final Current kSlipCurrent = Amps.of(120);

        // Initial configs for the drive and steer motors and the azimuth encoder; these
        // cannot be null.
        // Some configs will be overwritten; check the `with*InitialConfigs()` API
        // documentation.
        private static final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration();
        private static final TalonFXConfiguration steerInitialConfigs = new TalonFXConfiguration()
                        .withCurrentLimits(
                                        new CurrentLimitsConfigs()
                                                        // Swerve azimuth does not require much torque output, so we can
                                                        // set a relatively low
                                                        // stator current limit to help avoid brownouts without
                                                        // impacting performance.
                                                        .withStatorCurrentLimit(Amps.of(60))
                                                        .withStatorCurrentLimitEnable(true));
        private static final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
        // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
        private static final Pigeon2Configuration pigeonConfigs = new Pigeon2Configuration().withMountPose(new MountPoseConfigs().withMountPoseYaw(180));

        // CAN bus that the devices are located on;
        // All swerve devices must share the same CAN bus
        public static final CANBus kCANBus = new CANBus("Drive", "./logs/example.hoot");

        // Theoretical free speed (m/s) at 12 V applied output;
        // This needs to be tuned to your individual robot
        public static final LinearVelocity kSpeedAt12Volts = MetersPerSecond.of(5.12);

        // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
        // This may need to be tuned to your individual robot
        private static final double kCoupleRatio = 3.857142857142857;

        private static final double kDriveGearRatio = 6.026785714285714;
        private static final double kSteerGearRatio = 26.09090909090909;
        private static final Distance kWheelRadius = Inches.of(2);
        public static final double wheelCircumference = 2 * Math.PI * 0.0508;

        private static final boolean kInvertLeftSide = false;
        private static final boolean kInvertRightSide = true;

        private static final int kPigeonId = 20;

        // These are only used for simulation
        private static final MomentOfInertia kSteerInertia = KilogramSquareMeters.of(0.01);
        private static final MomentOfInertia kDriveInertia = KilogramSquareMeters.of(0.01);
        // Simulated voltage necessary to overcome friction
        private static final Voltage kSteerFrictionVoltage = Volts.of(0.2);
        private static final Voltage kDriveFrictionVoltage = Volts.of(0.2);

        public static final SwerveDrivetrainConstants DrivetrainConstants = new SwerveDrivetrainConstants()
                        .withCANBusName(kCANBus.getName())
                        .withPigeon2Id(kPigeonId)
                        .withPigeon2Configs(pigeonConfigs);

        private static final SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> ConstantCreator = new SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
                        .withDriveMotorGearRatio(kDriveGearRatio)
                        .withSteerMotorGearRatio(kSteerGearRatio)
                        .withCouplingGearRatio(kCoupleRatio)
                        .withWheelRadius(kWheelRadius)
                        .withSteerMotorGains(steerGains)
                        .withDriveMotorGains(driveGains)
                        .withSteerMotorClosedLoopOutput(kSteerClosedLoopOutput)
                        .withDriveMotorClosedLoopOutput(kDriveClosedLoopOutput)
                        .withSlipCurrent(kSlipCurrent)
                        .withSpeedAt12Volts(kSpeedAt12Volts)
                        .withDriveMotorType(kDriveMotorType)
                        .withSteerMotorType(kSteerMotorType)
                        .withFeedbackSource(kSteerFeedbackType)
                        .withDriveMotorInitialConfigs(driveInitialConfigs)
                        .withSteerMotorInitialConfigs(steerInitialConfigs)
                        .withEncoderInitialConfigs(encoderInitialConfigs)
                        .withSteerInertia(kSteerInertia)
                        .withDriveInertia(kDriveInertia)
                        .withSteerFrictionVoltage(kSteerFrictionVoltage)
                        .withDriveFrictionVoltage(kDriveFrictionVoltage);

        
        public static double MaxSpeed = 1.0 * Constants.kSpeedAt12Volts.in(MetersPerSecond); // kSpeedAt12Volts desired top speed
        public static double MaxAngularRate = RotationsPerSecond.of(0.75).in(RadiansPerSecond); // 3/4 of a rotation per second max angular velocity

        
                        // Front Left
        private static final int kFrontLeftDriveMotorId = 1;
        private static final int kFrontLeftSteerMotorId = 2;
        private static final int kFrontLeftEncoderId = 9;
        private static final Angle kFrontLeftEncoderOffset = Rotations.of(0.136474609375);
        private static final boolean kFrontLeftSteerMotorInverted = false;
        private static final boolean kFrontLeftEncoderInverted = false;

        private static final Distance kFrontLeftXPos = Inches.of(11);
        private static final Distance kFrontLeftYPos = Inches.of(11);

        // Front Right
        private static final int kFrontRightDriveMotorId = 3;
        private static final int kFrontRightSteerMotorId = 4;
        private static final int kFrontRightEncoderId = 10;
        private static final Angle kFrontRightEncoderOffset = Rotations.of(0.394775390625);
        private static final boolean kFrontRightSteerMotorInverted = false;
        private static final boolean kFrontRightEncoderInverted = false;

        private static final Distance kFrontRightXPos = Inches.of(11);
        private static final Distance kFrontRightYPos = Inches.of(-11);

        // Back Left
        private static final int kBackLeftDriveMotorId = 7;
        private static final int kBackLeftSteerMotorId = 8;
        private static final int kBackLeftEncoderId = 12;
        private static final Angle kBackLeftEncoderOffset = Rotations.of(-0.05908203125);
        private static final boolean kBackLeftSteerMotorInverted = false;
        private static final boolean kBackLeftEncoderInverted = false;

        private static final Distance kBackLeftXPos = Inches.of(-11);
        private static final Distance kBackLeftYPos = Inches.of(11);

        // Back Right
        private static final int kBackRightDriveMotorId = 5;
        private static final int kBackRightSteerMotorId = 6;
        private static final int kBackRightEncoderId = 11;
        private static final Angle kBackRightEncoderOffset = Rotations.of(-0.35888671875);
        private static final boolean kBackRightSteerMotorInverted = false;
        private static final boolean kBackRightEncoderInverted = false;

        private static final Distance kBackRightXPos = Inches.of(-11);
        private static final Distance kBackRightYPos = Inches.of(-11);

        public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontLeft = ConstantCreator
                        .createModuleConstants(
                                        kFrontLeftSteerMotorId, kFrontLeftDriveMotorId, kFrontLeftEncoderId,
                                        kFrontLeftEncoderOffset,
                                        kFrontLeftXPos, kFrontLeftYPos, kInvertLeftSide, kFrontLeftSteerMotorInverted,
                                        kFrontLeftEncoderInverted);
        public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontRight = ConstantCreator
                        .createModuleConstants(
                                        kFrontRightSteerMotorId, kFrontRightDriveMotorId, kFrontRightEncoderId,
                                        kFrontRightEncoderOffset,
                                        kFrontRightXPos, kFrontRightYPos, kInvertRightSide,
                                        kFrontRightSteerMotorInverted, kFrontRightEncoderInverted);
        public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackLeft = ConstantCreator
                        .createModuleConstants(
                                        kBackLeftSteerMotorId, kBackLeftDriveMotorId, kBackLeftEncoderId,
                                        kBackLeftEncoderOffset,
                                        kBackLeftXPos, kBackLeftYPos, kInvertLeftSide, kBackLeftSteerMotorInverted,
                                        kBackLeftEncoderInverted);
        public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackRight = ConstantCreator
                        .createModuleConstants(
                                        kBackRightSteerMotorId, kBackRightDriveMotorId, kBackRightEncoderId,
                                        kBackRightEncoderOffset,
                                        kBackRightXPos, kBackRightYPos, kInvertRightSide, kBackRightSteerMotorInverted,
                                        kBackRightEncoderInverted);

        /**
         * Creates a Drivetrain instance.
         * This should only be called once in your robot program,.
         */
        public static Drivetrain createDrivetrain() {
                return new Drivetrain(
                                DrivetrainConstants, FrontLeft, FrontRight, BackLeft, BackRight);
        }

        /**
         * Swerve Drive class utilizing CTR Electronics' Phoenix 6 API with the selected
         * device types.
         */
        public static class TunerSwerveDrivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> {
                /**
                 * Constructs a CTRE SwerveDrivetrain using the specified constants.
                 * <p>
                 * This constructs the underlying hardware devices, so users should not
                 * construct
                 * the devices themselves. If they need the devices, they can access them
                 * through
                 * getters in the classes.
                 *
                 * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
                 * @param modules             Constants for each specific module
                 */
                public TunerSwerveDrivetrain(
                                SwerveDrivetrainConstants drivetrainConstants,
                                SwerveModuleConstants<?, ?, ?>... modules) {
                        super(
                                        TalonFX::new, TalonFX::new, CANcoder::new,
                                        drivetrainConstants, modules);
                }

                /**
                 * Constructs a CTRE SwerveDrivetrain using the specified constants.
                 * <p>
                 * This constructs the underlying hardware devices, so users should not
                 * construct
                 * the devices themselves. If they need the devices, they can access them
                 * through
                 * getters in the classes.
                 *
                 * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
                 * @param odometryUpdateFrequency The frequency to run the odometry loop. If
                 *                                unspecified or set to 0 Hz, this is 250 Hz on
                 *                                CAN FD, and 100 Hz on CAN 2.0.
                 * @param modules                 Constants for each specific module
                 */
                public TunerSwerveDrivetrain(
                                SwerveDrivetrainConstants drivetrainConstants,
                                double odometryUpdateFrequency,
                                SwerveModuleConstants<?, ?, ?>... modules) {
                        super(
                                        TalonFX::new, TalonFX::new, CANcoder::new,
                                        drivetrainConstants, odometryUpdateFrequency, modules);
                }

                /**
                 * Constructs a CTRE SwerveDrivetrain using the specified constants.
                 * <p>
                 * This constructs the underlying hardware devices, so users should not
                 * construct
                 * the devices themselves. If they need the devices, they can access them
                 * through
                 * getters in the classes.
                 *
                 * @param drivetrainConstants       Drivetrain-wide constants for the swerve
                 *                                  drive
                 * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
                 *                                  unspecified or set to 0 Hz, this is 250 Hz
                 *                                  on
                 *                                  CAN FD, and 100 Hz on CAN 2.0.
                 * @param odometryStandardDeviation The standard deviation for odometry
                 *                                  calculation
                 *                                  in the form [x, y, theta]ᵀ, with units in
                 *                                  meters
                 *                                  and radians
                 * @param visionStandardDeviation   The standard deviation for vision
                 *                                  calculation
                 *                                  in the form [x, y, theta]ᵀ, with units in
                 *                                  meters
                 *                                  and radians
                 * @param modules                   Constants for each specific module
                 */
                public TunerSwerveDrivetrain(
                                SwerveDrivetrainConstants drivetrainConstants,
                                double odometryUpdateFrequency,
                                Matrix<N3, N1> odometryStandardDeviation,
                                Matrix<N3, N1> visionStandardDeviation,
                                SwerveModuleConstants<?, ?, ?>... modules) {
                        super(
                                        TalonFX::new, TalonFX::new, CANcoder::new,
                                        drivetrainConstants, odometryUpdateFrequency,
                                        odometryStandardDeviation, visionStandardDeviation, modules);
                }
        }

        public static final class VisionConstants {
                public static final String kCameraName = "photonvision";

                // old constraints (might want to use again)

                public static final TrapezoidProfile.Constraints kXConstraints = new TrapezoidProfile.Constraints(1, 2);
                public static final TrapezoidProfile.Constraints kYConstraints = new TrapezoidProfile.Constraints(.5,
                                2);
                public static final TrapezoidProfile.Constraints kOmegaConstraints = new TrapezoidProfile.Constraints(3,
                                8);

                public static final double kVisionMaxDistanceMeters = 5;

                public static final double kTranslationTolerance = 0.02;
                public static final double kThetaTolerance = Units.degreesToRadians(0);

                // // TODO: tune!
                // public static final TrapezoidProfile.Constraints kDefaultXYContraints = new TrapezoidProfile.Constraints(
                //                 m_drive.maxSpeed * 0.3,
                //                 Swerve.maxAngularVelocity);

                // public static final TrapezoidProfile.Constraints kDefaultOmegaConstraints = new TrapezoidProfile.Constraints(
                //                 Swerve.maxAngularVelocity * 0.2,
                //                 Swerve.maxAngularVelocity);

                // // TODO: tune!
                // public static final double X_kP = 1.25;
                // public static final double X_kI = 0.3;
                // public static final double X_kD = 0.0;

                // public static final double Y_kP = 1.25;
                // public static final double Y_kI = 0.3;
                // public static final double Y_kD = 0.0;

                // public static final double THETA_kP = 1.5;
                // public static final double THETA_kI = 0.5;
                // public static final double THETA_kD = 0.15;

                // TODO: ensure validity of measurements
                // public static final Transform3d kRobotToCameraLeft = new Transform3d(
                //                 new Translation3d(0.3719, 0.27305, 0.09),
                //                 new Rotation3d(0, .1745, 0));
                // public static final Transform3d kRobotToCameraRight = new Transform3d(
                //                 new Translation3d(0.3719, -0.27305, 0.09),
                //                 new Rotation3d(0, .1745, 0));
                // -0.698

                public static final double kFieldLengthMeters = 17.55;
                public static final double kFieldWidthMeters = 8.05;
                // DOCS:
                // https://firstfrc.blob.core.windows.net/frc2025/FieldAssets/2025FieldDrawings-FieldLayoutAndMarking.pdf
                // Z-Rotation is Yaw, X-Rotation is Pitch
                // Rotation3d has roll first, then pitch, then yaw

                // public static final List<AprilTag> kBlueTagList;
        }
}
