package frc.robot;

// import static frc.robot.Constants.Swerve.angleGearRatio;
import static edu.wpi.first.units.Units.Amps;
import static edu.wpi.first.units.Units.Inches;
import static edu.wpi.first.units.Units.KilogramSquareMeters;
import static edu.wpi.first.units.Units.MetersPerSecond;
import static edu.wpi.first.units.Units.RadiansPerSecond;
import static edu.wpi.first.units.Units.Rotations;
import static edu.wpi.first.units.Units.RotationsPerSecond;
import static edu.wpi.first.units.Units.Volts;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.CANcoderConfiguration;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.MountPoseConfigs;
import com.ctre.phoenix6.configs.Pigeon2Configuration;
import com.ctre.phoenix6.configs.Slot0Configs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.StaticFeedforwardSignValue;
import com.ctre.phoenix6.swerve.SwerveDrivetrain;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.ClosedLoopOutputType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.DriveMotorArrangement;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.SteerFeedbackType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.SteerMotorArrangement;
import com.ctre.phoenix6.swerve.SwerveModuleConstantsFactory;

import com.ctre.phoenix6.signals.NeutralModeValue;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.trajectory.TrapezoidProfile;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.Current;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.units.measure.LinearVelocity;
import edu.wpi.first.units.measure.MomentOfInertia;
import edu.wpi.first.units.measure.Voltage;
import frc.robot.subsystems.drive.Drivetrain;
import frc.util.COTSFalconSwerveConstants;

// TODO: Remove duplicates


// Generated by the 2026 Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class Constants {
        // public static double MaxSpeed = 1.0 * Constants.kSpeedAt12Volts.in(MetersPerSecond); // kSpeedAt12Volts desired
                                                                        // second max angular
                    
        public static final String kRobotIdFile = "/home/lvuser/id.txt";
        public static final String kCurrentLogFolder = "/home/lvuser/currentLogs";
        public static final double kNominalVoltage = 12.0;
        public static final int kCANTimeoutMs = 250;
        public static final double kTimestepSeconds = 0.02;
        public static final double kInchesToMeters = 0.0254;
        public static final double kRIOLoopTime = 0.02;
        // Both sets of gains need to be tuned to your individual robot.

        // Motor constants
        // TODO: Set these to the right values
        public static final double kFalconSensorUnitsPerRotation = 2048; // pulses per rotation
        public static final double kFalconWindingsResistanceOhms = 12.0 / 257;
        public static final double kFalconTorquePerAmp = 4.69 / 257;
        public static final double kFalconOutputUnitsFull = 1023;
        public static final double kFalconOutputUnitsPerVolt = kFalconOutputUnitsFull / kNominalVoltage;
        public static final double kFalconFreeSpeedRotationsPerSecond = 6380.0 / 60.0;
        public static final double kSecondsPer100Ms = 0.1;

        public static final double k775FreeSpeedRotationsPerSecond = 18730.0 / 60.0;

        public static final COTSFalconSwerveConstants chosenModule = COTSFalconSwerveConstants
                        .SDSMK5n(COTSFalconSwerveConstants.driveGearRatios.SDSMK5n_L1);

        // The steer motor uses any SwerveModule.SteerRequestType control request with
        // the
        // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
        private static final Slot0Configs steerGains = new Slot0Configs() // PID
                        .withKP(40).withKI(0).withKD(0.2)
                        .withKS(0.15).withKV(1.5).withKA(0)
                        .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
        // When using closed-loop control, the drive motor uses the control
        // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
        private static final Slot0Configs driveGains = new Slot0Configs()
                        .withKP(0.1).withKI(0).withKD(0)
                        .withKS(0.2).withKV(2).withKA(0.03);

       
    // The closed-loop output type to use for the steer motors;
    // This affects the PID/FF gains for the steer motors
    private static final ClosedLoopOutputType kSteerClosedLoopOutput = ClosedLoopOutputType.Voltage;
    // The closed-loop output type to use for the drive motors;
    // This affects the PID/FF gains for the drive motors
    private static final ClosedLoopOutputType kDriveClosedLoopOutput = ClosedLoopOutputType.Voltage;

    // The type of motor used for the drive motor
    private static final DriveMotorArrangement kDriveMotorType = DriveMotorArrangement.TalonFX_Integrated;
    // The type of motor used for the drive motor
    private static final SteerMotorArrangement kSteerMotorType = SteerMotorArrangement.TalonFX_Integrated;

    // The remote sensor feedback type to use for the steer motors;
    // When not Pro-licensed, Fused*/Sync* automatically fall back to Remote*
    private static final SteerFeedbackType kSteerFeedbackType = SteerFeedbackType.FusedCANcoder;

    // The stator current at which the wheels start to slip;
    // This needs to be tuned to your individual robot
    private static final Current kSlipCurrent = Amps.of(120);

    // Initial configs for the drive and steer motors and the azimuth encoder; these cannot be null.
    // Some configs will be overwritten; check the `with*InitialConfigs()` API documentation.
    private static final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration().withCurrentLimits(new CurrentLimitsConfigs().withStatorCurrentLimit(60).withStatorCurrentLimitEnable(true));
    private static final TalonFXConfiguration steerInitialConfigs = new TalonFXConfiguration()
        .withCurrentLimits(
            new CurrentLimitsConfigs()
                // Swerve azimuth does not require much torque output, so we can set a relatively low
                // stator current limit to help avoid brownouts without impacting performance.
                .withStatorCurrentLimit(Amps.of(30))
                .withStatorCurrentLimitEnable(true)
        );
    private static final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
    // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
    private static final Pigeon2Configuration pigeonConfigs = null;

    // CAN bus that the devices are located on;
    // All swerve devices must share the same CAN bus
    public static final CANBus kCANBus = new CANBus("Drive");

    // Theoretical free speed (m/s) at 12 V applied output;
    // This needs to be tuned to your individual robot
    public static final LinearVelocity kSpeedAt12Volts = MetersPerSecond.of(4.54);
        public static double MaxSpeed = .9 * .6525 * Constants.kSpeedAt12Volts.in(MetersPerSecond); // kSpeedAt12Volts desired 67 strat
                                                                                             // top speed
        public static double MaxAngularRate = RotationsPerSecond.of(0.75).in(RadiansPerSecond); // 3/4 of a rotation per
                        
    // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
    // This may need to be tuned to your individual robot 67
    private static final double kCoupleRatio = 3.857142857142857;

    private static final double kDriveGearRatio = 7.026785714285714;
    private static final double kSteerGearRatio = 26.09090909090909;
    private static final Distance kWheelRadius = Inches.of(2);

    private static final boolean kInvertLeftSide = false;
    private static final boolean kInvertRightSide = true;

    private static final int kPigeonId = 20;

    // These are only used for simulation
    private static final MomentOfInertia kSteerInertia = KilogramSquareMeters.of(0.01);
    private static final MomentOfInertia kDriveInertia = KilogramSquareMeters.of(0.01);
    // Simulated voltage necessary to overcome friction
    private static final Voltage kSteerFrictionVoltage = Volts.of(0.2);
    private static final Voltage kDriveFrictionVoltage = Volts.of(0.2);

    public static final SwerveDrivetrainConstants DrivetrainConstants = new SwerveDrivetrainConstants()
            .withCANBusName(kCANBus.getName())
            .withPigeon2Id(kPigeonId)
            .withPigeon2Configs(pigeonConfigs);

    private static final SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> ConstantCreator =
        new SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
            .withDriveMotorGearRatio(kDriveGearRatio)
            .withSteerMotorGearRatio(kSteerGearRatio)
            .withCouplingGearRatio(kCoupleRatio)
            .withWheelRadius(kWheelRadius)
            .withSteerMotorGains(steerGains)
            .withDriveMotorGains(driveGains)
            .withSteerMotorClosedLoopOutput(kSteerClosedLoopOutput)
            .withDriveMotorClosedLoopOutput(kDriveClosedLoopOutput)
            .withSlipCurrent(kSlipCurrent)
            .withSpeedAt12Volts(kSpeedAt12Volts)
            .withDriveMotorType(kDriveMotorType)
            .withSteerMotorType(kSteerMotorType)
            .withFeedbackSource(kSteerFeedbackType)
            .withDriveMotorInitialConfigs(driveInitialConfigs)
            .withSteerMotorInitialConfigs(steerInitialConfigs)
            .withEncoderInitialConfigs(encoderInitialConfigs)
            .withSteerInertia(kSteerInertia)
            .withDriveInertia(kDriveInertia)
            .withSteerFrictionVoltage(kSteerFrictionVoltage)
            .withDriveFrictionVoltage(kDriveFrictionVoltage);


    // Front Left
    private static final int kFrontLeftDriveMotorId = 1;
    private static final int kFrontLeftSteerMotorId = 2;
    private static final int kFrontLeftEncoderId = 9;
    private static final Angle kFrontLeftEncoderOffset = Rotations.of(-0.356201171875);
    private static final boolean kFrontLeftSteerMotorInverted = false;
    private static final boolean kFrontLeftEncoderInverted = false;

    private static final Distance kFrontLeftXPos = Inches.of(11);
    private static final Distance kFrontLeftYPos = Inches.of(11);

    // Front Right
    private static final int kFrontRightDriveMotorId = 3;
    private static final int kFrontRightSteerMotorId = 4;
    private static final int kFrontRightEncoderId = 10;
    private static final Angle kFrontRightEncoderOffset = Rotations.of(0.393798828125);
    private static final boolean kFrontRightSteerMotorInverted = false;
    private static final boolean kFrontRightEncoderInverted = false;

    private static final Distance kFrontRightXPos = Inches.of(11);
    private static final Distance kFrontRightYPos = Inches.of(-11);

    // Back Left
    private static final int kBackLeftDriveMotorId = 5;
    private static final int kBackLeftSteerMotorId = 6;
    private static final int kBackLeftEncoderId = 11;
    private static final Angle kBackLeftEncoderOffset = Rotations.of(0.053955078125);
    private static final boolean kBackLeftSteerMotorInverted = false;
    private static final boolean kBackLeftEncoderInverted = false;

    private static final Distance kBackLeftXPos = Inches.of(-11);
    private static final Distance kBackLeftYPos = Inches.of(11);

    // Back Right
    private static final int kBackRightDriveMotorId = 7;
    private static final int kBackRightSteerMotorId = 8;
    private static final int kBackRightEncoderId = 12;
    private static final Angle kBackRightEncoderOffset = Rotations.of(0.440185546875);
    private static final boolean kBackRightSteerMotorInverted = false;
    private static final boolean kBackRightEncoderInverted = false;

    private static final Distance kBackRightXPos = Inches.of(-11);
    private static final Distance kBackRightYPos = Inches.of(-11);


    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontLeft =
        ConstantCreator.createModuleConstants(
            kFrontLeftSteerMotorId, kFrontLeftDriveMotorId, kFrontLeftEncoderId, kFrontLeftEncoderOffset,
            kFrontLeftXPos, kFrontLeftYPos, kInvertLeftSide, kFrontLeftSteerMotorInverted, kFrontLeftEncoderInverted
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontRight =
        ConstantCreator.createModuleConstants(
            kFrontRightSteerMotorId, kFrontRightDriveMotorId, kFrontRightEncoderId, kFrontRightEncoderOffset,
            kFrontRightXPos, kFrontRightYPos, kInvertRightSide, kFrontRightSteerMotorInverted, kFrontRightEncoderInverted
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackLeft =
        ConstantCreator.createModuleConstants(
            kBackLeftSteerMotorId, kBackLeftDriveMotorId, kBackLeftEncoderId, kBackLeftEncoderOffset,
            kBackLeftXPos, kBackLeftYPos, kInvertLeftSide, kBackLeftSteerMotorInverted, kBackLeftEncoderInverted
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackRight =
        ConstantCreator.createModuleConstants(
            kBackRightSteerMotorId, kBackRightDriveMotorId, kBackRightEncoderId, kBackRightEncoderOffset,
            kBackRightXPos, kBackRightYPos, kInvertRightSide, kBackRightSteerMotorInverted, kBackRightEncoderInverted
        );
        /**
         * Swerve Drive class utilizing CTR Electronics' Phoenix 6 API with the selected
         * device types.
         */
        public static class TunerSwerveDrivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> {
                /**
                 * Constructs a CTRE SwerveDrivetrain using the specified constants.
                 * <p>
                 * This constructs the underlying hardware devices, so users should not
                 * construct
                 * the devices themselves. If they need the devices, they can access them
                 * through
                 * getters in the classes.
                 *
                 * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
                 * @param modules             Constants for each specific module
                 */
                public TunerSwerveDrivetrain(
                                SwerveDrivetrainConstants drivetrainConstants,
                                SwerveModuleConstants<?, ?, ?>... modules) {
                        super(
                                        TalonFX::new, TalonFX::new, CANcoder::new,
                                        drivetrainConstants, modules);
                }

                /**
                 * Constructs a CTRE SwerveDrivetrain using the specified constants.
                 * <p>
                 * This constructs the underlying hardware devices, so users should not
                 * construct
                 * the devices themselves. If they need the devices, they can access them
                 * through
                 * getters in the classes.
                 *
                 * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
                 * @param odometryUpdateFrequency The frequency to run the odometry loop. If
                 *                                unspecified or set to 0 Hz, this is 250 Hz on
                 *                                CAN FD, and 100 Hz on CAN 2.0.
                 * @param modules                 Constants for each specific module
                 */
                public TunerSwerveDrivetrain(
                                SwerveDrivetrainConstants drivetrainConstants,
                                double odometryUpdateFrequency,
                                SwerveModuleConstants<?, ?, ?>... modules) {
                        super(
                                        TalonFX::new, TalonFX::new, CANcoder::new,
                                        drivetrainConstants, odometryUpdateFrequency, modules);
                }

                /**
                 * Constructs a CTRE SwerveDrivetrain using the specified constants.
                 * <p>
                 * This constructs the underlying hardware devices, so users should not
                 * construct
                 * the devices themselves. If they need the devices, they can access them
                 * through
                 * getters in the classes.
                 *
                 * @param drivetrainConstants       Drivetrain-wide constants for the swerve
                 *                                  drive
                 * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
                 *                                  unspecified or set to 0 Hz, this is 250 Hz
                 *                                  on
                 *                                  CAN FD, and 100 Hz on CAN 2.0.
                 * @param odometryStandardDeviation The standard deviation for odometry
                 *                                  calculation
                 *                                  in the form [x, y, theta]ᵀ, with units in
                 *                                  meters
                 *                                  and radians
                 * @param visionStandardDeviation   The standard deviation for vision
                 *                                  calculation
                 *                                  in the form [x, y, theta]ᵀ, with units in
                 *                                  meters
                 *                                  and radians
                 * @param modules                   Constants for each specific module
                 */
                public TunerSwerveDrivetrain(
                                SwerveDrivetrainConstants drivetrainConstants,
                                double odometryUpdateFrequency,
                                Matrix<N3, N1> odometryStandardDeviation,
                                Matrix<N3, N1> visionStandardDeviation,
                                SwerveModuleConstants<?, ?, ?>... modules) {
                        super(
                                        TalonFX::new, TalonFX::new, CANcoder::new,
                                        drivetrainConstants, odometryUpdateFrequency,
                                        odometryStandardDeviation, visionStandardDeviation, modules);
                }
        }
        public static final class AimConstants{

                public static final double kTargetAngleTolerance = .13; // at 4 meters .02 rotations wil allow .5metres of tolerance

        }
        public static final class VisionConstants {
                public static final String kCameraName = "photonvision";

                // old constraints (might want to use again)

                public static final TrapezoidProfile.Constraints kXConstraints = new TrapezoidProfile.Constraints(1, 2);
                public static final TrapezoidProfile.Constraints kYConstraints = new TrapezoidProfile.Constraints(.5,
                                2);
                public static final TrapezoidProfile.Constraints kOmegaConstraints = new TrapezoidProfile.Constraints(3,
                                8);

                public static final double kVisionMaxDistanceMeters = 5;

                public static final double kTranslationTolerance = 0.02;
                public static final double kThetaTolerance = Units.degreesToRadians(0);

                // // TODO: tune!
                // public static final TrapezoidProfile.Constraints kDefaultXYContraints = new
                // TrapezoidProfile.Constraints(
                // m_drive.maxSpeed * 0.3,
                // Swerve.maxAngularVelocity);

                // public static final TrapezoidProfile.Constraints kDefaultOmegaConstraints =
                // new TrapezoidProfile.Constraints(
                // Swerve.maxAngularVelocity * 0.2,
                // Swerve.maxAngularVelocity);

                // // TODO: tune!
                // public static final double X_kP = 1.25;
                // public static final double X_kI = 0.3;
                // public static final double X_kD = 0.0;

                // public static final double Y_kP = 1.25;
                // public static final double Y_kI = 0.3;
                // public static final double Y_kD = 0.0;

                // public static final double THETA_kP = 1.5;
                // public static final double THETA_kI = 0.5;
                // public static final double THETA_kD = 0.15;

                // TODO: ensure validity of measurements
                // public static final Transform3d kRobotToCameraLeft = new Transform3d(
                // new Translation3d(0.3719, 0.27305, 0.09),
                // new Rotation3d(0, .1745, 0));
                // public static final Transform3d kRobotToCameraRight = new Transform3d(
                // new Translation3d(0.3719, -0.27305, 0.09),
                // new Rotation3d(0, .1745, 0));
                // -0.698

                public static final double kFieldLengthMeters = 17.55;
                public static final double kFieldWidthMeters = 8.05;
                // DOCS:
                // https://firstfrc.blob.core.windows.net/frc2025/FieldAssets/2025FieldDrawings-FieldLayoutAndMarking.pdf
                // Z-Rotation is Yaw, X-Rotation is Pitch
                // Rotation3d has roll first, then pitch, then yaw

                // public static final List<AprilTag> kBlueTagList;
        }

        public static final class AnglerConstants {

                public static final double kPAngler = 50;
                public static final double kIAngler = 0.15;
                public static final double kDAngler = 0.1;
                public static final double kVAngler = 0.14;
                public static final double kAAngler = 0.012;

                public static final int kAnglerPort = 30;
                public static final boolean kAnglerClockwisePositive = true;

        }

        public static final class ShooterConstants {

                public static final double kPShooter = 0.4;
                public static final double kIShooter = 0.15;
                public static final double kDShooter = 0;
                public static final double kVShooter = 0.15;
                public static final double kAShooter = 0.012;

                public static final int kShooterPortLeft = 28;
                public static final int kShooterPortRight = 22;
                public static final boolean kShooterLeftClockwisePositive = false;
                public static final boolean kShooterRightClockwisePositive = false;

        }

        public static final class FeederConstants {
                public static final double kPFeeder = 0.5;
                public static final double kIFeeder = 0.02;
                public static final double kDFeeder = 0.0;
                public static final double kVFeeder = 0.20;
                public static final double kAFeeder = 0.015;

                public static final int kFeederPort = 25;
                public static final boolean kFeederClockwisePositive = true;

        }

        public static final class WindexerConstants {
                public static final boolean kWindexerClockwisePositive = true;

                public static final double kPWindexer = 1;
                public static final double kIWindexer = 0.0;
                public static final double kDWindexer = 0.0;
        }

        public static final class IntakeConstants {
                public static final boolean kIntakeClockwisePositive = true;
                public static final boolean kWinchClockwisePositive = true;

                public static final double kPIntakeRoller = 0;
                public static final double kIIntakeRoller = 0;
                public static final double kDIntakeRoller = 0;
                public static final double kVIntakeRoller = 0.12;
                public static final double kAIntakeRoller = 0.012;

                public static final double kPIntakeWinch = 0.2;
                public static final double kIIntakeWinch = 0;
                public static final double kDIntakeWinch = 0;
                public static final double kVIntakeWinch = .03; //change it to lower value (.23)
                public static final double kAIntakeWinch = .0025; //maybe lower this a bit too
        }

        public static final class ClimberConstants {
                public static final int kClimberPort = 30;

                public static final double kSClimber = 0;
                public static final double kVClimber = 0;
                public static final double kAClimber = 0;

                public static final double kPClimber = 0;
                public static final double kIClimber = 0;
                public static final double kDClimber = 0;

                public static final double kClimberVelocity = 0;
                public static final double kClimberAcceleration = 0;

                public static final boolean kClimberClockwisePositive = false;

                public static final double kClimberErrorTolerance = 1;
        }

        public static final class OIConstants {
                public static final int kDriverPort = 0;
                public static final int kOperatorPort = 1;

                public static final double kDriverRightXDeadband = 0.05;
                public static final double kDriverLeftXDeadband = 0.05;
                public static final double kDriverLeftYDeadband = 0.05;

                public static final double kTriggerThreshold = 0.1;
        }

        public static final class DriveConstants {
                // Max speed teleoperated
                public static final double kTeleopMaxSpeedMetersPerSecond = 3; // meters per second
                public static final double kTeleopMaxAngularSpeedRadiansPerSecond = 4; // radians per second
        }

        public static final class Swerve {

                public static final int pigeonID = 20;
                public static final boolean invertGyro = false; // Always ensure Gyro is CCW+ CW-

                public static final COTSFalconSwerveConstants chosenModule = COTSFalconSwerveConstants
                                .SDSMK5n(COTSFalconSwerveConstants.driveGearRatios.SDSMK5n_L1);

                /* Drivetrain Constants (2026 robot: module corners at +/-11 in) */
                public static final double lengthBetweenModules = Units.inchesToMeters(22);
                public static final double widthBetweenModules = Units.inchesToMeters(22);
                public static final double wheelCircumference = chosenModule.wheelCircumference;

                /*
                 * Swerve Kinematics -- standard WPILib frame: +X forward, +Y LEFT, CCW+.
                 * Index order is the module number: Mod0 FL, Mod1 FR, Mod2 BR, Mod3 BL, and each
                 * translation is that module's physical corner (matches the Tuner X k*XPos/YPos).
                 */
                public static final SwerveDriveKinematics swerveKinematics = new SwerveDriveKinematics(
                                new Translation2d(Swerve.lengthBetweenModules / 2.0, Swerve.widthBetweenModules / 2.0),
                                new Translation2d(Swerve.lengthBetweenModules / 2.0, -Swerve.widthBetweenModules / 2.0),
                                new Translation2d(-Swerve.lengthBetweenModules / 2.0, -Swerve.widthBetweenModules / 2.0),
                                new Translation2d(-Swerve.lengthBetweenModules / 2.0,
                                                Swerve.widthBetweenModules / 2.0));

                /* Module Gear Ratios (exact Tuner X values; these feed SensorToMechanismRatio) */
                public static final double driveGearRatio = 7.026785714285714;
                public static final double angleGearRatio = 26.09090909090909;

                /*
                 * Motor / encoder inverts, straight from the Tuner X project (same semantics as
                 * Phoenix's SwerveModuleConstants: true -> Clockwise_Positive, false ->
                 * CounterClockwise_Positive). Tuner X verified these on the real modules, so
                 * with them the steer motor, the CANcoder and the WPILib module angle all count
                 * CCW+ together. All four modules share the steer/encoder flags; the per-module
                 * drive flag lives in Mod0..Mod3 below.
                 */
                public static final boolean angleMotorInvert = kFrontLeftSteerMotorInverted;
                public static final boolean canCoderInvert = kFrontLeftEncoderInverted;

                /* Swerve Current Limiting */
                public static final int angleContinuousCurrentLimit = 40;
                public static final int anglePeakCurrentLimit = 80;
                public static final double anglePeakCurrentDuration = 0.1;
                public static final boolean angleEnableCurrentLimit = true;

                public static final int driveContinuousCurrentLimit = 35;
                public static final int drivePeakCurrentLimit = 60;
                public static final double drivePeakCurrentDuration = 0.1;
                public static final boolean driveEnableCurrentLimit = true;

                /*
                 * These values are used by the drive falcon to ramp in open loop and closed
                 * loop driving.
                 */
                public static final double openLoopRamp = 0.25;
                public static final double closedLoopRamp = 0.0;

                /* Angle Motor PID Values */
                public static final double angleKP = 40;
                public static final double angleKI = 0.0;
                public static final double angleKD = 0.05;
                public static final double angleKF = 0;
                public static final double angleKV = 0;

                /* Drive Motor PID Values */
                public static final double driveKP = 0.2;
                public static final double driveKI = 0;
                public static final double driveKD = 0.0;
                public static final double driveKF = 0.0;

                /* Drive Motor Characterization Values */
                public static final double driveKS = 0;
                public static final double driveKV = 0.124;
                public static final double driveKA = 0;

                /*
                 * Swerve Profiling Values
                 * TUNE: teleop is faster than the old Phoenix setup (which capped requests at
                 * Constants.MaxSpeed ~2.67 m/s) and rotation is slower (3 vs ~4.71 rad/s).
                 * Adjust maxAngularVelocity here and the shaping in DriveConstants to taste.
                 */
                /** Meters per Second (Tuner kSpeedAt12Volts) */
                public static final double maxSpeed = 4.54;
                /** Radians per Second */
                public static final double maxAngularVelocity = 3;

                /* Neutral Modes */
                public static final NeutralModeValue angleNeutralMode = NeutralModeValue.Brake;
                public static final NeutralModeValue driveNeutralMode = NeutralModeValue.Brake;

                /*
                 * Module Specific Constants -- CAN IDs, CANcoder magnet offsets and drive inverts
                 * copied from the 2026 Tuner X config above (kFrontLeft*, kFrontRight*, ...).
                 * The offset is applied as the CANcoder MagnetOffset exactly like Tuner X does,
                 * so getCanCoder() reads 0 with the wheel pointing forward; nothing here needs
                 * re-zeroing unless a magnet physically moves.
                 */
                /* Front Left Module - Module 0 */
                public static final class Mod0 {
                        public static final int driveMotorID = 1;
                        public static final int angleMotorID = 2;
                        public static final int canCoderID = 9;
                        public static final Rotation2d angleOffset = Rotation2d.fromRotations(-0.356201171875);
                        public static final frc.util.SwerveModuleConstants constants = new frc.util.SwerveModuleConstants(
                                        driveMotorID, angleMotorID, canCoderID, angleOffset, kInvertLeftSide);
                }

                /* Front Right Module - Module 1 */
                public static final class Mod1 {
                        public static final int driveMotorID = 3;
                        public static final int angleMotorID = 4;
                        public static final int canCoderID = 10;
                        public static final Rotation2d angleOffset = Rotation2d.fromRotations(0.393798828125);
                        public static final frc.util.SwerveModuleConstants constants = new frc.util.SwerveModuleConstants(
                                        driveMotorID, angleMotorID, canCoderID, angleOffset, kInvertRightSide);
                }

                /* Back Right Module - Module 2 */
                public static final class Mod2 {
                        public static final int driveMotorID = 7;
                        public static final int angleMotorID = 8;
                        public static final int canCoderID = 12;
                        public static final Rotation2d angleOffset = Rotation2d.fromRotations(0.440185546875);
                        public static final frc.util.SwerveModuleConstants constants = new frc.util.SwerveModuleConstants(
                                        driveMotorID, angleMotorID, canCoderID, angleOffset, kInvertRightSide);
                }

                /* Back Left Module - Module 3 */
                public static final class Mod3 {
                        public static final int driveMotorID = 5;
                        public static final int angleMotorID = 6;
                        public static final int canCoderID = 11;
                        public static final Rotation2d angleOffset = Rotation2d.fromRotations(0.053955078125);
                        public static final frc.util.SwerveModuleConstants constants = new frc.util.SwerveModuleConstants(
                                        driveMotorID, angleMotorID, canCoderID, angleOffset, kInvertLeftSide);
                }
        }
}
